destination = "subtitles"
proxy = ""
download_root = "https://kitsunekko.net/dirlist.php?dir=subtitles/japanese/"
timeout = 120
skip_older = "5 days"
[headers]
User-Agent = "Mozilla/5.0 (Windows NT 10.0; rv:108.0) Gecko/20100101 Firefox/108.0"
Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
Accept-Charset = "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
Accept-Encoding = "none"
Accept-Language = "en-US,en;q=0.8"
Connection = "keep-alive"
